[package]
name = "lcy_lib_c"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
nalgebra = "0.31.0"
rand = "0.8.5"
libc="0.2.125"